//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordCrackerMaster {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordCrackerMaster.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anders:5en6G6MezRroT3XKqkdPOmY/BfQ=
        ///peter:qmz4syDsnnyBP+NQeqczRv/kJP4=
        ///michael:rIFGj9xqLUA0T0J8xiGCuMlfnvM=
        ///vibeke:EQ91A67FOpjss4uW8kV570lnSa0=
        ///lars:cupd+wYwjxfNBtLY4oc9WWhVDZU=
        ///poul:94roVc1d8UZEtbK9LBF3vuo0wkg=
        ///susanne:qVs4ZslBdqp0Xp2jcyt4RIpP5+8=
        ///per:AXPaVO/3DmqNsW2uPJw9ZJxf9lc=
        ///ebbe:vE8YzmcA85cX1cTVa89XN1TwPhw=
        ///steen:8Ssn+7nvQr6yRLdKLLHBJIX5ck0=
        ///mohammed:e5E3g74Ju2HGGnhzMCZ55DmzFgc=
        ///mogens:O6BE8Nyx/TWEI6VuCyHsI71zxV0=
        ///.
        /// </summary>
        internal static string passwords {
            get {
                return ResourceManager.GetString("passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///A acid
        ///A b station
        ///A battery
        ///A bond
        ///A derrick
        ///A la marengo
        ///A la maryland
        ///A level
        ///A major
        ///A minor
        ///A natural
        ///A one
        ///A pole
        ///A powder
        ///A star
        ///A switchboard
        ///A-b-c book
        ///A-b-c method
        ///A-flat
        ///A-flat major
        ///A-shaped
        ///A-sharp
        ///Aani
        ///Aaron
        ///Aaronic
        ///Aaronical
        ///Aaronite
        ///Aaronitic
        ///Aaru
        ///Ab
        ///Ababdeh
        ///Ababua
        ///Abadite
        ///Abama
        ///Abanic
        ///Abantes
        ///Abarambo
        ///Abaris
        ///Abasgi
        ///Abassin
        ///Abatua
        ///Abba
        ///Abbadide
        ///Abbasside
        ///Abbie
        ///Abbott papyrus
        ///Abby
        ///Abderian
        ///Abderite
        ///Abdiel
        ///Abdominales
        ///Abdul-baha
        ///Abe
        ///Abel
        ///Abelia
        ///Abelian
        ///Abelicea
        ///Abelite
        ///Abelmoschus
        ///Abelonian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webster_dictionary {
            get {
                return ResourceManager.GetString("webster_dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A
        ///Achomawi
        ///Achordata
        ///Achorion
        ///Achras
        ///Achroanthes
        ///Achromatiaceae
        ///Achromatium
        ///Achromobacter
        ///Adam tiler
        ///Aegina
        ///Aeginetan
        ///Aeginetan marbles
        ///Aeginetic
        ///Aegipan
        ///Aegisthus
        ///Aegithalos
        ///Aegithognathae
        ///Aegle
        ///Aegopodium
        ///Aeluroidea
        ///Aeolia
        ///Aeolian
        ///Aeolic
        ///Aeolicism
        ///Aeolidae
        ///Aeolididae
        ///Aeolis
        ///Aeolism
        ///Aeolist
        ///Aepyceros
        ///Aepyornis
        ///Aepyornithidae
        ///Aepyornithiformes
        ///Aequi
        ///Aequian
        ///Aequiculi
        ///Aequipalpia
        ///Aglossa
        ///Aglypha
        ///Aglyphodonta
        ///Aglyphodontia
        ///Agnatha
        ///Agnathostomata
        ///Agnes
        ///Agnoetae
        ///Agnoete
        ///Agnoetism
        ///Agnoite
        ///Agnostus
        ///Al tais
        ///Al tar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webster_dictionary_reduced {
            get {
                return ResourceManager.GetString("webster_dictionary_reduced", resourceCulture);
            }
        }
    }
}
